models/News.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string $title
 * @property string $text
 * @property string $date_creation
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'text'], 'required'],
            [['title', 'text'], 'string'],
            [['date_creation'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'text' => 'Text',
            'date_creation' => 'Date Creation',
        ];
    }
}

models/NewsAdd.php
<?php


namespace app\models;


use yii\base\Model;

class NewsAdd extends Model
{
    public $title;
    public $description;

    public function rules()
    {
        return [
            [['title', 'description'], 'required'],
        ];
    }
}

models/Product.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property string $img
 * @property string $model
 * @property int $price
 * @property int $price_sale
 * @property string|null $date
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['img', 'model', 'price', 'price_sale'], 'required'],
            [['img', 'model'], 'string'],
            [['price', 'price_sale'], 'integer'],
            [['date'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'img' => 'Img',
            'model' => 'Model',
            'price' => 'Price',
            'price_sale' => 'Price Sale',
            'date' => 'Date',
        ];
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\News;
use app\models\NewsAdd;
use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use app\models\Product;


class SiteController extends Controller
{
    CONST SITE_PATH = '/web/site';

    private $request;

    public function __construct($id, $module, $config = [])
    {
        $this->request = Yii::$app->request;

        parent::__construct($id, $module, $config);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        Yii::$app->view->title = 'Техномаркет';
        $products = Product::find()
            ->orderBy('id DESC')
            ->limit(10)
            ->all();

        return $this->render('index.tpl', ['products' => $products]);
    }

    /**
     * Displays login.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionProduct()
    {
        $request = Yii::$app->request;
        if ($request->get()) {
            $id = (int)$request->get('id');
            $product = Product::find()
                ->where(['id' => $id])
                ->one();
            if (is_null($product)) {
                throw new ForbiddenHttpException('Product not found');
            }

            return $this->render('product.tpl', ['product' => $product]);
        }

        return $this->redirect('/web');
    }

    /**
     * Displays news.
     *
     * @return string
     */
    public function actionNews()
    {
        Yii::$app->view->title = 'Новости';

        $news = News::find()
            ->orderBy('id DESC')
            ->limit(10)
            ->all();

        return $this->render('news.tpl', ['news_all' => $news]);
    }

    /**
     * Displays news_info.
     *
     * @return string
     * @throws ForbiddenHttpException
     */
    public function actionNewsinfo()
    {
        Yii::$app->view->title = 'Новости';

        if ($this->request->get()) {
            $id = (int)$this->request->get('id');
            $news = News::find()
                ->where(['id' => $id])
                ->one();
            if (is_null($news)) {
                throw new ForbiddenHttpException('News not found');
            }

            return $this->render('news-info.tpl', ['news' => $news]);
        }

        return $this->redirect(self::SITE_PATH . '/news');
    }

    public function actionNewsadd()
    {
        Yii::$app->view->title = 'Добавить новсть';
        $news = new News();

        $form_model = new NewsAdd();
        if ($form_model->load(\Yii::$app->request->post())) {
            $title = $form_model->title;
            $description = $form_model->description;

            $news->title = $title;
            $news->text = $description;

            $news->save();

            return $this->redirect(self::SITE_PATH . '/news');
        }

        return $this->render('news-add', compact('form_model'));
    }

    public function actionNewsdelete()
    {
        if ($this->request->get()) {
            $id = (int)$this->request->get('id');
            $news = News::find()
                ->where(['id' => $id])
                ->one();
            if (is_null($news)) {
                throw new ForbiddenHttpException('News not found');
            }
            $news->delete();
        }

        return $this->redirect(self::SITE_PATH . '/news');
    }
}

views/layouts/feedback.php
<div class="map container">
    <noscript>
        <figure>
            <img src="<?= Yii::$app->request->baseUrl ?>/uploads/map.jpg" width="940" height="447"
                 alt="Мы на карте">
        </figure>
    </noscript>
    <div class="map-script"></div>
    <a href="#" class="map-close"></a>
</div>

<div class="feedback container">
    <a href="#" class="feedback-close"></a>
    <form action="" method="post">
        <div class="feedback-userdata">
            <div class="feedback-block clearfix">
                <div class="feedback-left-column">
                    <label class="feedback-data" for="feedback-login">Ваше имя:</label>
                    <input type="text" name="login" id="feedback-login" placeholder="Представьтесь, пожалуйста">
                </div>
                <div class="feedback-right-column">
                    <label class="feedback-data" for="feedback-email">Ваш e-mail:</label>
                    <input type="email" name="email" id="feedback-email" placeholder="Для отправки ответа" required>
                </div>
            </div>
            <label class="feedback-data" for="feedback-textarea">Текст письма:</label>
            <textarea name="text" id="feedback-textarea" placeholder="В свободной форме" required rows="5"></textarea>
        </div>
        <div class="feedback-block-buttons">
            <button type="submit" class="feedback-btn">Отправить</button>
            <a href="#" class="feedback-btn feedback-cancel">Отмена</a>
        </div>
    </form>
</div>
<div class="cart-notification">
    <a href="#" class="cart-notification-close"></a>
    <form action="" method="post">
        <p class="cart-notification-title">Товар добавлен в корзину!</p>
        <div class="cart-notification-decision">
            <button type="submit" class="cart-order-btn">Оформить заказ</button>
            <a href="#" class="cart-cancel-btn">Продолжить покупки</a>
        </div>
    </form>
</div>

views/layouts/footer.php
<footer>
    <div class="footer-bottom-panel">
        <div class="container clearfix">
            <div style="text-align: center; color: #FFF">
                <p>© <?php echo date("Y"); ?> Компания «Техномарт» Все права защищены</p>
            </div>
        </div>
    </div>
</footer>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    echo Nav::widget([
        'options' => ['class' => 'navbar navbar-expand-lg navbar-light bg-light justify-content-between'],
        'items' => [
            ['label' => 'Главная', 'url' => Yii::$app->homeUrl],
            ['label' => 'Новости', 'url' => ['/site/news']],
            ['label' => 'Контакты', 'url' => ['/site/contact']],
            ['label' => 'О нас', 'url' => ['/site/about']]
        ],
    ]);
    ?>

    <div class="container-fluid">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
        <?php include 'service.php' ?>
        <?php include 'feedback.php' ?>
        <?php include 'footer.php' ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/service.php
<section class="service">
    <div class="container">
        <div class="service-intro">
            <h2 class="service-title">Сервисы</h2>
            <p class="service-title-info">Хороший интернет-магазин отличается от плохого не только ценами!</p>
            <p class="service-title-info">Мы стараемся изо всех сил чтобы сделать ваши покупки приятными.</p>
        </div>
        <div class="service-columns clearfix">
            <div class="left-column service-list-column">
                <ul>
                    <li>
                        <a href="#" class="service-list-active">Доставка</a>
                    </li>
                    <li>
                        <a href="#">Гарантия</a>
                    </li>
                    <li>
                        <a href="#">Кредит</a>
                    </li>
                </ul>
            </div>
            <div class="right-column service-details-column">
                <section class="service-details-block service-details-delivery service-details-active">
                    <h2 class="service-details-title">Доставка</h2>
                    <p class="service-details-info service-delivery-info">Мы с одовольствием доставим ваш товар
                        прямо к вашему подьезду совершенно бесплатно!</p>
                    <p class="service-details-info service-delivery-info">Ведь мы неплохо заработаем поднимая его на
                        ваш этаж.</p>
                </section>
                <section class="service-details-block service-details-warrianty">
                    <h2 class="service-details-title">Гарантия</h2>
                    <p class="service-details-info service-warrianty-info">Если купленный у нас товар поломается или
                        заискрит, а также в случае пожара, спровоцированного его возгаранием, вы всегда можете быть
                        уверены в нашей гарантии. Мы обменяем сгоревший товар на новый.</p>
                    <p class="service-details-info service-warrianty-info">Дом уж восстановите как-нибудь сами.</p>
                </section>
                <section class="service-details-block service-details-credit">
                    <h2 class="service-details-title">Кредит</h2>
                    <p class="service-details-info service-credit-info">Залезть в долговую яму стало проще!</p>
                    <p class="service-details-info service-credit-info">Кредитные консультанты придут вам на
                        помощь.</p>
                    <a href="#" class="service-btn">Отправить заявку</a>
                </section>
            </div>
        </div>
    </div>
</section>
<section class="company container clearfix">
    <section class="left-column company-promo-column">
        <h2 class="company-promo-title">«Компания Техномарт»</h2>
        <p class="company-promo-info">Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для ремонта
            и строительства не оставит равнодушными любителей сэкомномть на гастарбайтерах.</p>
        <p class="company-promo-info">Мы можем доставить товар в самые отдаленные точки России! Техномарт работает
            со многими транспортными компаниями:</p>
        <ul class="company-promo-list">
            <li>Деловые Линии</li>
            <li>Автотрейдинг</li>
            <li>ЖелДорЭкспедиция</li>
        </ul>
        <a hre class="right-column company-contacts-column">
            <h2f="#" class="company-about-btn">Подробнее о компании</a>
    </section>
</section>

views/site/news-add.php
<?php

use yii\base\Widget;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<main>
    <section class="news">
        <div class="container">
            <?php $form = ActiveForm::begin() ?>
            <?= $form->field($form_model, 'title')->label('Заголовок'); ?>
            <?= $form->field($form_model, 'description')->label('Описание')->textarea() ?>
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            <?php ActiveForm::end() ?>
        </div>
    </section>
</main>